# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64" # a.k.a. Debian 12
  config.vm.hostname = "dfirbian"
  config.vm.post_up_message = "Don't forget to create a snapshot and disable the eth0 interface before starting the analysis!"
  
  # Configures the host-only network adapter on the virtual machine. This will be important for isolating the machine from the LAN later.
  config.vm.network "private_network", ip: "192.168.56.10"
  
  # Mount the shared directory in read-only mode to prevent the guest machine from writing files to the host.
  config.vm.synced_folder "../guest", "/mnt/host", mount_options: ["ro"]
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision :shell, :path => "setup_dfirbian.sh", :privileged => false
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 2
  end
end
